on:
  pull_request:
    types: [opened]

jobs:
  fact-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run fact-checking script
        run: python fact_check.py ${{ github.event.pull_request.head.repo.clone_url }} ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.number }} ${{ secrets.TOKEN }}
